name: Integrations CI

on:
  push:
    branches:
      - '**'
    paths:
      - '**'
      - '!**.md'
    tags:
      - '*'
  pull_request:
    branches:
      - master
      - develop
    paths:
      - '**'
      - '!**.md'

jobs:
  integrations:
    runs-on: ubuntu-18.04

    # name: Node ${{ matrix.node-version }}

    services:
      mongodb:
        image: mongo:3.6
        ports:
          - 27017:27017

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    # https://github.com/actions/cache/blob/master/examples.md#node---yarn
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache Node.js modules
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-integrations-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-integrations-${{ hashFiles('yarn.lock') }}
          ${{ runner.os }}-yarn-integrations-
          ${{ runner.os }}-yarn-

    - name: Install
      run: |
        yarn install

    - name: Lint
      run: |
        yarn lint

    - name: Tsc
      run: |
        yarn tsc

    - name: Test
      run: |
        yarn test
      env:
        TEST_MONGO_URL: mongodb://localhost/test
        GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID
        GOOGLE_CLIENT_SECRET: GOOGLE_CLIENT_SECRET
        ENCRYPTION_KEY: aksljdklwjdaklsjdkwljaslkdjwkljd
        DOMAIN: http://localhost:3400
        MAIN_APP_DOMAIN: http://localhost:3400

    - name: Build
      if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' )
      run: |
        yarn build

    - name: Build docker image [push]
      if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' )
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker build -t erxes/erxes-integrations:${GITHUB_REF#refs/heads/} -f Dockerfile .
        docker push erxes/erxes-integrations:${GITHUB_REF#refs/heads/}

    - name: Build docker image [tag]
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      run: |
        docker build -t erxes/erxes-integrations:${GITHUB_REF#refs/tags/} -f Dockerfile .
        docker push erxes/erxes-integrations:${GITHUB_REF#refs/tags/}
